apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  generateName: cleanup-after-sync-
  labels:
    codefresh.io/cert: cleanup-job  
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "20" 
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "10"
      restartPolicy: Never
  backoffLimit: 2    
