apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-

resources:
- ../../base

components:
  - ../../variants/prod

patchesStrategicMerge:
- deployment.yml
- version.yml
- replicas.yml
- settings.yml
- service.yml

