apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  type: NodePort
  selector:
    app: trivial-go-web-app
  ports:
      - nodePort: 31002
        protocol: TCP
        port: 8080
        name: prod-port
